server.port=8080
spring.data.mongodb.uri=mongodb://localhost:27017/siddharoodha_temple
spring.data.mongodb.database=siddharoodha_temple

# JWT Properties
temple.jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
temple.jwt.expiration=86400000

# Email SMTP Settings for Booking Confirmation
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=vasanta11223@gmail.com
spring.mail.password=mbet gdco bidv shir
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.ssl.trust=*

